=== evandrix/Splat/_modules/PEAK-0.5a3/PEAK-0.5a3/build/PEAK/src/ZConfig/doc/schema.dtd
<!--
  *************************************************************************
  Copyright (c) 2002, 2003 Zope Corporation and Contributors.
  All Rights Reserved.

  This software is subject to the provisions of the Zope Public License,
  Version 2.0 (ZPL).  A copy of the ZPL should accompany this distribution.
  THIS SOFTWARE IS PROVIDED "AS IS" AND ANY AND ALL EXPRESS OR IMPLIED
  WARRANTIES ARE DISCLAIMED, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
  WARRANTIES OF TITLE, MERCHANTABILITY, AGAINST INFRINGEMENT, AND FITNESS
  FOR A PARTICULAR PURPOSE.
  *************************************************************************
  -->

<!-- DTD for ZConfig schema documents. -->

<!ELEMENT schema (description?, metadefault?, example?,
                  import*,
                  (sectiontype | abstracttype)*,
                  (section | key | multisection | multikey)*)>
<!ATTLIST schema
          extends    NMTOKEN  #IMPLIED
          prefix     NMTOKEN  #IMPLIED
          handler    NMTOKEN  #IMPLIED
          keytype    NMTOKEN  #IMPLIED
          datatype   NMTOKEN  #IMPLIED>

<!ELEMENT component (description?, (sectiontype | abstracttype)*)>
<!ATTLIST component
          prefix     NMTOKEN  #IMPLIED>

<!ELEMENT extension (description?, (sectiontype | abstracttype)*)>
<!ATTLIST extension
          prefix     NMTOKEN  #IMPLIED>

<!ELEMENT import EMPTY>
<!ATTLIST import
          file       CDATA    #IMPLIED
          package    NMTOKEN  #IMPLIED
          src        CDATA    #IMPLIED>

<!ELEMENT description (#PCDATA)*>
<!ATTLIST description
          format     NMTOKEN  #IMPLIED>

<!ELEMENT metadefault (#PCDATA)*>
<!ELEMENT example     (#PCDATA)*>

<!ELEMENT sectiontype (description?, 
                       (section | key | multisection | multikey)*)>
<!ATTLIST sectiontype
          name       NMTOKEN  #REQUIRED
          prefix     NMTOKEN  #IMPLIED
          keytype    NMTOKEN  #IMPLIED
          datatype   NMTOKEN  #IMPLIED
          implements NMTOKEN  #IMPLIED
          extends    NMTOKEN  #IMPLIED>

<!ELEMENT abstracttype (description?)>
<!ATTLIST abstracttype
          name       NMTOKEN  #REQUIRED
          prefix     NMTOKEN  #IMPLIED>

<!ELEMENT key (description?, metadefault?, example?)>
<!ATTLIST key
          name       CDATA    #REQUIRED
          attribute  NMTOKEN  #IMPLIED
          datatype   NMTOKEN  #IMPLIED
          handler    NMTOKEN  #IMPLIED
          required   (yes|no) "no"
          default    CDATA    #IMPLIED>

<!ELEMENT multikey (description?, metadefault?, example?, default*)>
<!ATTLIST multikey
          name       CDATA    #REQUIRED
          attribute  NMTOKEN  #IMPLIED
          datatype   NMTOKEN  #IMPLIED
          handler    NMTOKEN  #IMPLIED
          required   (yes|no) "no">

<!ELEMENT section (description?)>
<!ATTLIST section
          name       CDATA    #REQUIRED
          attribute  NMTOKEN  #IMPLIED
          type       NMTOKEN  #REQUIRED
          handler    NMTOKEN  #IMPLIED
          required   (yes|no) "no">

<!ELEMENT multisection (description?)>
<!ATTLIST multisection
          name       CDATA    #REQUIRED
          attribute  NMTOKEN  #IMPLIED
          type       NMTOKEN  #REQUIRED
          handler    NMTOKEN  #IMPLIED
          required   (yes|no) "no">

=== evandrix/Splat/_partial_bytecode_exec/PEAK-0.5a3/PEAK-0.5a3/build/PEAK/src/peak/tools/version/component.xml
<?xml version = '1.0' encoding = 'ISO-8859-1' ?>
<!DOCTYPE component SYSTEM '../../../ZConfig/doc/schema.dtd' >

<component prefix="peak.tools.version">





































  <sectiontype name="Edit" datatype=".config.Editor.fromZConfig">

    <description>
        A pattern of changes that need to be applied to a set of files
    </description>

    <multikey
        name="File" attribute="filenames" datatype="existing-file" required="yes">
        <description>
        Name of a file to be edited.  You may repeat this key to apply
        the same set of changes to more than one file.
        </description>
    </multikey>


    <multikey
        name="Match" attribute="edits" datatype=".config.Match.fromString">
        <description>
        A string to be matched in the file.  The string may contain '%(item)s'
        escapes that will be used to match or insert portions of a current
        or updated version number.  If the string contains any punctuation, you
        must surround it with single or double quotes.  You may supply more
        than one Match line, in which case they must be listed in the same
        order that they will occur in each edited file.

        If any string listed by a Match line is not found in one of the edited
        files, an error will occur, and no changes will be made to any of the
        files.  (You can override this behavior for an individual string by
        putting the word "optional" before the string you want to match, e.g.
        "Match optional 'something I want to match'".
        </description>
    </multikey>

  </sectiontype>







  <sectiontype name="Module" datatype=".config.Module.fromZConfig">

    <description>
        A versionable entity within a software project; projects must have at
        least one "module".

        XXX A current limitation of the system is that no file may be used in
        more than one Module, or even more than one Edit within the same
        module!
    </description>

    <key name="Name" attribute="name" datatype="string" required="yes">
        <description>The name of the module, e.g. "PEAK"</description>
    </key>

    <key name="Scheme" attribute="schemeName" datatype="string"
         default="default">
        <description>
            The version numbering scheme used by this module.  If not
            specified, it defaults to "default".  In any case, the scheme
            must be defined by a "Scheme" section in the top-level
            configuration.
        </description>
    </key>

    <multisection name="*" type="Edit" attribute="editors" required="yes">
        <description>
            The edits needed to update the module's version.
        </description>
    </multisection>

  </sectiontype>









  <sectiontype name="Formats" datatype=".config.getFormats" keytype="string">

    <description>
        A collection of named formats for a numbering scheme.  Each key in
        a Formats section is the name of a format.  Its value can be a 'remap',
        'optional', or 'string'.  For example:

          %lt;Formats%gt;
          trailer   remap status "a%(build)s" "b%(build)s" "c%(build)s" "%(dot-maint)s"
          dot-maint optional build ".%(build)s" ""
          full      string "%(major)s.%(minor)s %(status)s %(build)s"
          short     "%(major)s.%(minor)s%(trailer)s"
          %lt;/Formats%gt;

        This example defines two string formats ("full" and "short"), one
        optional format ("dot-maint"), and one remap format ("trailer").
        (Notice that if you want a string to contain spaces or nonalphabetic
        characters, you must enclose it in single or double quotes.)

        An 'remap' format is used to supply alternate names for a 'choice' part
        in the numbering scheme.  The example above remaps a part called
        'status' to use 'a', 'b', or 'c' in place of the original name.  This
        is useful for abbreviations or language/spelling variants between
        formats.  Notice that %() escapes can be used.

        An 'optional' format is used to implement a simple choice, based on
        whether another part or format is empty or zero.  In the example above,
        the 'dot-maint' format will be either a '.' followed by the build
        number, or an empty string if the 'build' part of the version number is
        zero or empty.

        A 'string' format is a format that begins with the word 'string' (as
        in the "full" example above) or a quoted string (as in the "short"
        example above).  String formats have any %() escapes converted to the
        named parts or formats.  So, the version 1.2alpha3 would be rendered
        as '1.2 alpha 3' in "full" format, and '1.2a3' in "short" format.
        Meanwhile, version 1.9.0 would be rendered as '1.9 final 0' in "full"
        format, and as simply '1.9' in "short" format.
    </description>


    <key name="+" attribute="formats" datatype="string" required="yes">
        <description>
            Each line in a Formats section consists of a format name, followed
            by a definition.  See the description for the Formats section for
            more information.
        </description>
    </key>

  </sectiontype>
































  <sectiontype name="Scheme" datatype=".config.Scheme.fromZConfig">

    <description>A version numbering scheme</description>

    <key name="DefaultFormat" attribute="defaultFormat" datatype="string">
        <description>
        Name of the format that should be used when displaying a version number
        that follows this scheme.  For example, if the scheme has a "full"
        format defined, then one might use "DefaultFormat full" to declare that
        the "full" format should be used when displaying a version number.
        Note that if you specify a non-existent format, an error will occur
        if you attempt to display a version number.

        If you do not specify a default format, versions will be displayed in
        a simple format that breaks out each part of the version number by
        name.
        </description>
    </key>

    <multikey name="part" attribute="partDefs" datatype="string" required="yes">
        <description>
        </description>
    </multikey>

    <section name="*" type="Formats" attribute="formatDefs" />

  </sectiontype>


</component>

=== evandrix/Splat/benchmarks/_modules/PEAK-0.5a3/PEAK-0.5a3/src/peak/running/component.xml
<?xml version = '1.0' encoding = 'ISO-8859-1' ?>
<!DOCTYPE component SYSTEM '../../ZConfig/doc/schema.dtd' >

<component prefix="peak.running">

  <abstracttype name='running.Task'>
    <description>
      Any component that can be part of a running.commands.EventDriven
      application.
    </description>
  </abstracttype>






























  <sectiontype  name="AdaptiveTask"
                datatype=".daemons.AdaptiveTask.fromZConfig"
                implements="running.Task">

    <description>Common configuration for adaptive tasks.</description>

    <key name="RunEvery"
         attribute="runEvery"
	 datatype="time-interval"
	 required="yes">
	 <description>
	 The default number of seconds between attempts to run this task.
	 </description>
    </key>

    <key name="Priority"
         attribute="priority"
         datatype="integer"
         required="yes">
         <description>
         The priority of this task, relative to others.  Higher numbers
         are higher priority.  Tasks with higher priority will run before
         tasks with lower priority, if more than one task is ready to run.
         Higher priority tasks will *starve* lower priority tasks if there
         continues to be work available for the higher priority task, and its
         'MinimumIdle' setting is low.
         </description>
    </key>

    <key name="MinimumIdle"
         attribute="minimumIdle"
	 datatype="time-interval">
	 <description>
	 The minimum number of seconds the task will wait between *successful*
	 attempts to run.  Defaults to the same as 'RunEvery'.
	 </description>
    </key>




    <key name="IncreaseIdleBy"
         attribute="increaseIdleBy"
         datatype="time-interval">
         <description>
         Each time the task is attempted and fails (i.e. has no work to do),
         increase the idle interval by this duration, until 'MaximumIdle' is
         reached.  The idle interval will reset to the 'MinimumIdle' once the
         task successfully does work, otherwise it will stay at 'MaximumIdle'.
         'IncreaseIdleBy' defaults to zero if not set.
         </description>
    </key>

    <key name="MultiplyIdleBy"
         attribute="multiplyIdleBy"
         datatype="float">
         <description>
         Each time the task is attempted and fails (i.e. has no work to do),
         multiply the idle interval by this number before adding
         'IncreaseIdleBy' (if set), until 'MaximumIdle' is reached.  The idle
         interval will reset to the 'MinimumIdle' once the task successfully
         does work, otherwise it will stay at 'MaximumIdle'.
         'MultiplyIdleBy' Defaults to 1 if not set.
         </description>
    </key>

    <key name="MaximumIdle"
         attribute="maximumIdle"
	 datatype="time-interval">
	 <description>
	 The maximum number of seconds the task will wait between *unsuccessful*
	 attempts to run.  Defaults to a number that will allow the idle interval
     to increase three times, if either 'MultiplyIdleBy' or 'IncreaseIdleBy'
     are set.  Otherwise, defaults to the same as 'RunEvery'.
	 </description>
    </key>






    <key name="LockURL" attribute="lockName" datatype="string">
	 <description>
	 The PEAK URL of an object to be used as a lock.  The lock will be acquired
     before (and released after) the task's getWork() and doWork() methods
     are called.  If no URL is supplied, no lock will be acquired or released.
	 </description>
    </key>

    <key name="logURL" attribute="logName" datatype="string">
	 <description>
	 The PEAK URL of the logger that this task should use to record events.
     It defaults to 'logger:daemons.TaskName', where TaskName is
     the task's section name in the ZConfig file.
	 </description>
    </key>

  </sectiontype>
























  <sectiontype  name="CleanupFiles"
                datatype=".daemons.FileCleaner.fromZConfig"
                implements="running.Task"
                extends="AdaptiveTask">

    <description>Remove old files from a directory</description>

    <key name="Directory" attribute="directory" datatype="existing-directory"
         required="yes">
         <description>
         The directory that needs to be cleaned of files.  The directory must
         exist at configuration time.  Note that you can also specify
         subdirectories of this directory as part of the 'MatchFiles' setting.
         </description>
    </key>

    <key name="MatchFiles" attribute="matchFiles" datatype="string"
         default="*">
         <description>
         A filename "glob" (i.e. match pattern) that will be used to search
         'Directory' for files to delete.  The pattern may contain '?' (match
         a single arbitrary character), '*' (match any number of characters
         that are not path separators, and '[]' (match one of the characters
         between the brackets.  The pattern defaults to '*' (i.e., all files)
         if not specified.
         </description>
    </key>

    <key name="DeleteIfOlderThan" attribute="olderThan"
         datatype="time-interval"
         required="yes">
         <description>
         Files that match the 'MatchFiles' pattern in 'Directory' that were
         last modified at least this long ago will be deleted.
         </description>
    </key>

  </sectiontype>



  <sectiontype  name="URLChecker"
                datatype=".daemons.URLChecker.fromZConfig"
                implements="running.Task"
                extends="AdaptiveTask">

    <description>Check a URL for activity and start a service if needed.
    </description>

    <key name="CheckURL" attribute="url" datatype="string" required="yes">
         <description>
         The URL of the resource to check.  This can be a stream resource
         (e.g. 'file:', 'http:', or 'ftp:' URLs), a managed connection
         (e.g. 'ldap:', 'pgsql:', etc.), or any resource that can be adapted to
         the 'peak.running.ICheckableResource' interface.
         </description>
    </key>

    <key name="RestartWith" attribute="restartURL" datatype="string"
         required="yes">
         <description>
         URL of a command to invoke when needed to restart the service
         controlling 'CheckURL'.
         </description>
    </key>

  </sectiontype>

</component>

=== evandrix/Splat/_partial_bytecode_exec/PEAK-0.5a3/PEAK-0.5a3/src/peak/running/EventDriven.xml
<?xml version = '1.0' encoding = 'ISO-8859-1' ?>
<!DOCTYPE schema SYSTEM '../../ZConfig/doc/schema.dtd' >

<schema datatype=".commands.EventDriven.fromZConfig" prefix="peak.running">

<import package="peak.running"/>

<key name="StopAfter" attribute="stopAfter" datatype="time-interval">
    <description>
    After this many seconds, stop and exit the application as soon as the
    active task completes.  Defaults to 0, which means never stop.
    </description>
</key>

<key name="IdleTimeout" attribute="idleTimeout" datatype="time-interval">
    <description>
    Stop and exit the application as soon as it has been idle (i.e. no
    'activityOccurred()' messages have been sent to the main loop) for this
    many seconds.  Defaults to 0, which means don't check for activity.
    </description>
</key>

<key name="RunAtLeast" attribute="runAtLeast" datatype="time-interval">
    <description>
    Wait this many seconds before enabling the 'IdleTimeout'.  Note that this
    setting has no effect if 'IdleTimeout' is 0.  'RunAtLeats' defaults to
    0, which means idle checking commences immediately.
    </description>
</key>

<multisection name="*"
              type="running.Task"
              attribute="components"
              required="yes">
    <description>
    An EventDriven application must include one or more sections describing
    tasks.
    </description>
</multisection>

</schema>

=== evandrix/Splat/_partial_bytecode_exec/PEAK-0.5a3/PEAK-0.5a3/build/PEAK/src/peak/tools/supervisor/Supervisor.xml
<?xml version = '1.0' encoding = 'ISO-8859-1' ?>
<!DOCTYPE schema SYSTEM '../../../ZConfig/doc/schema.dtd' >

<schema extends="pkgfile:peak.running/EventDriven.xml"
        prefix="peak.tools.supervisor"
        datatype=".process.ProcessSupervisor.fromZConfig">

    <description>
    This schema describes the configuration of a ProcessSupervisor: a PEAK
    command that forks copies of itself as subprocesses, and monitors them.
    For the original vision document and background, see:

    http://www.eby-sarna.com/pipermail/peak/2003-August/000697.html

    (Note...  there are probably other things we might want to configure later,
    such as the signals sent to stop subprocesses, signals monitored by the
    parent process, etc.)
    </description>

    <key name="Command" attribute="cmdText" datatype="string" default="">
        <description>
        The command to be run as a subprocess.  This is a standard PEAK command
        line; i.e. a URL or peak.running.shortcut item, followed by its
        arguments.
        </description>
    </key>

    <key name="PidFile" attribute="pidFile" datatype="existing-dirpath"
         required="yes">

        <description>
        Name of a file where the supervisor process' process ID (PID) will be
        stored.  If the supervisor is started when a supervisor is already
        running (as determined by this file), the existing process will be
        killed.
        </description>

    </key>



    <key name="MinProcesses" attribute="minChildren" datatype="integer"
        default="1">

        <description>
        Minimum number of child processes to keep running.  If the number of
        active processes falls below this level, new ones will be started
        (every 'StartInterval' seconds) to raise the number of active processes
        to this level.
        </description>

    </key>


    <key name="MaxProcesses" attribute="maxChildren" datatype="integer"
        default="4">

        <description>
        Maximum number of child processes allowed.  The supervisor will not
        start new processes if there are already this many processes active.
        </description>

    </key>


    <key name="StartInterval" attribute="startInterval"
        datatype="time-interval" default="15s">

        <description>
        Amount of time to wait after starting a subprocess, before starting
        another one.  In other words, there will be at this many seconds
        between subprocess starts.
        </description>

    </key>







    <multikey name="Import" attribute="importModules"
        datatype="peak.util.imports.importString">

        <description>
        You may specify one or more 'Import' keys, each naming a module to
        be imported at application startup.  The purpose of this is to allow
        you to ensure that certain modules have been imported before child
        processes are started, thus preventing the child process from needing
        to import them.  This can speed the startup of child process, and
        perhaps even reduce memory consumption on some operating systems.
        </description>

    </multikey>

    <key name="StartupLock" attribute="startLockURL" datatype="string">
        <description>
        An optional URL, specifying an ILock that will be used to ensure only
        one supervisor attempts startup at a given moment.  If not supplied, it
        defaults to 'flockfile:PIDFILE.start' where PIDFILE is the supplied
        'PidFile' setting.  So, if you set 'PidFile' to '/foo/bar/baz.pid',
        then 'StartupLock' will default to 'flockfile:/foo/bar/baz.pid.start'.
        </description>
    </key>

    <key name="PidLock" attribute="pidLockURL" datatype="string">
        <description>
        An optional URL, specifying an ILock that will be used to ensure only
        one supervisor attempts to modify the PidFile at a given moment.  If
        not supplied, it defaults to 'flockfile:PIDFILE.lock' where PIDFILE is
        the supplied 'PidFile' setting.  So, if you set 'PidFile' to
        '/foo/bar/baz.pid', then 'StartupLock' will default to
        'flockfile:/foo/bar/baz.pid.lock'.
        </description>
    </key>

</schema>

=== evandrix/Splat/_modules/PEAK-0.5a3/PEAK-0.5a3/build/PEAK/src/peak/tools/version/Version.xml
<?xml version = '1.0' encoding = 'ISO-8859-1' ?>
<!DOCTYPE schema SYSTEM '../../../ZConfig/doc/schema.dtd' >

<schema
    datatype=".app.VersionConfig.fromZConfig"
    prefix="peak.tools.version"
>

<import package="peak.tools.version"/>

<key name="DataFile" attribute="datafile" datatype="existing-file">
    <description>
    </description>
</key>

<multisection name="*" type="Scheme" attribute="schemes" required="yes">
    <description>
    </description>
</multisection>

<multisection name="*" type="Module" attribute="modules" required="yes">
    <description>
    </description>
</multisection>

</schema>
